# Generated by Django 3.0.8 on 2020-07-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('imgPath', models.ImageField(upload_to='')),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=30)),
                ('userRating', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
